workerPoolSpecs:
- machineSpec:
    machineType: n1-standard-4
    acceleratorType: NVIDIA_TESLA_T4
    acceleratorCount: 1
  replicaCount: 1
  containerSpec:
    imageUri: europe-west1-docker.pkg.dev/dtumlops-484509/mlops-container-images/main:latest
    env:
    - name: WANDB_API_KEY
      value: ${WANDB_API_KEY}
    - name: DATA_ROOT
      value: /gcs/mlops116/data/processed  
    args:
    - wandb
    - agent
    - sergi-luponsantacana-danmarks-tekniske-universitet-dtu/mlops_g116/goglpg6f

