workerPoolSpecs:
- machineSpec:
    machineType: n1-highmem-16
    acceleratorType: NVIDIA_TESLA_T4
    acceleratorCount: 1
  replicaCount: 1
  containerSpec:
    imageUri: europe-west1-docker.pkg.dev/dtumlops-484509/mlops-container-images/main:latest
    env:
    - name: WANDB_API_KEY
      value: ${WANDB_API_KEY}
    - name: DATA_ROOT
      value: /gcs/mlops116/data/processed 
    - name: RUN_SNAKEVIZ
      value: "0"
    - name: RUN_TENSORBOARD
      value: "0"
    - name: OPEN_TENSORBOARD
      value: "0"
    - name: WANDB_AGENT_DISABLE_FLAPPING
      value: "true"
    - name: WANDB_INIT_TIMEOUT
      value: "180"
    command: ["wandb", "agent"]
    args:
    #- wandb
    #- agent
    - sergi-luponsantacana-danmarks-tekniske-universitet-dtu/mlops_g116/vortb3g8
