steps:
- name: "alpine"
  id: "Replace values in the training config"
  entrypoint: "sh"
  args:
    - "-c"
    - |
      apk add --no-cache gettext
      envsubst < ${_VERTEX_TRAIN_CONFIG} > ${_VERTEX_TRAIN_CONFIG}.tmp
      mv ${_VERTEX_TRAIN_CONFIG}.tmp ${_VERTEX_TRAIN_CONFIG}
  secretEnv: ['WANDB_API_KEY']

# ⚠️ Recomendación: no mostrar el config (imprime el secreto en logs)
# - name: 'alpine'
#   id: "Show config"
#   waitFor: ['Replace values in the training config']
#   entrypoint: "sh"
#   args:
#     - "-c"
#     - |
#       cat ${_VERTEX_TRAIN_CONFIG}

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Train on vertex AI'
  waitFor: ['Replace values in the training config']
  args: [
    'ai',
    'custom-jobs',
    'create',
    '--region',
    'europe-west1',
    '--display-name',
    'vertex-train-secret',
    '--config',
    '${_VERTEX_TRAIN_CONFIG}',
  ]

substitutions:
  _VERTEX_TRAIN_CONFIG: 'configs/vertex/vertex.yaml'


availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/WANDB_API_KEY/versions/latest
    env: 'WANDB_API_KEY'

options:
  logging: CLOUD_LOGGING_ONLY
