name: mlops_g116_sweep
project: mlops_g116
method: random
metric:
  goal: minimize
  name: train_loss
parameters:
  lr:
    min: 0.0001
    max: 0.01
    distribution: log_uniform
  model:
    values: [simple, resnet18, densenet121]
  optimizer:
    values: [adam, sgd]
  batch_size:
    values: [32, 64]
  epochs:
    values: [2, 3]
run_cap: 3
command:
  - ${env}
  - ${interpreter}
  - -m
  - mlops_g116.train_hydra
  - hyperparameters.lr=${lr}
  - hyperparameters.batch_size=${batch_size}
  - hyperparameters.epochs=${epochs}
  - model=${model}
  - optimizer=${optimizer}
