name: mlops_g116_sweep
project: mlops_g116
method: grid

metric:
  goal: maximize
  name: test/accuracy

parameters:
  lr:
    values: [0.0001, 0.001, 0.01]
  batch_size:
    values: [32, 64]
  epochs:
    value: 10
  model:
    values: [simple, resnet18, densenet121]
  optimizer:
    values: [adam, sgd]

# opcional: limita el total de runs si quieres
# run_cap: 12

command:
  - ${env}
  - python3
  - -m
  - mlops_g116.main
  - hyperparameters.lr=${lr}
  - hyperparameters.batch_size=${batch_size}
  - hyperparameters.epochs=${epochs}
  - model=${model}
  - optimizer=${optimizer}
