name: mlops_g116_sweep
project: mlops_g116
method: grid

metric:
  goal: maximize
  name: test/accuracy

parameters:
  lr:
    values: [0.0001, 0.001, 0.01]
  batch_size:
    value: 32
  epochs:
    value: 10
  model:
    values: [simple, resnet18]
  optimizer:
    values: [adam, sgd]

run_cap: 10

# opcional: limita el total de runs si quieres
# run_cap: 12

command:
  - ${env}
  - python3
  - -m
  - mlops_g116.sweep_runner
