name: mlops_g116_sweep
project: mlops_g116
method: grid

metric:
  goal: maximize
  name: test/accuracy

parameters:
  hyperparameters.lr:
    values: [0.0001, 0.001, 0.01]
  hyperparameters.batch_size:
    values: [32, 64]
  hyperparameters.epochs:
    value: 10
  model:
    values: [simple, resnet18, densenet121]
  optimizer:
    values: [adam, sgd]

# opcional: limita el total de runs si quieres
# run_cap: 12

command:
  - ${env}
  - ${interpreter}
  - -m
  - mlops_g116.main
  - hyperparameters.lr=${hyperparameters.lr}
  - hyperparameters.batch_size=${hyperparameters.batch_size}
  - hyperparameters.epochs=${hyperparameters.epochs}
  - model=${model}
  - optimizer=${optimizer}

